import Head from 'next/head'
import Image from 'next/image'


import {connect} from 'react-redux'
import {setUser} from 'Redux/reducers/user/action'
import React, { useEffect, useState } from 'react';
import Request from 'Api/request'
import { retrievePokemonLists } from 'Redux/reducers/pokemon/action'

const Home = (props:any) => {
const asyncRequest = async(func:any,handle:any)=>{
const test = await func
handle(test)
}

useEffect(()=>{
  asyncRequest(Request.retrievePokemonLists(), props.retrievePokemonLists)
},[props.retrievePokemonLists])

  return (
    <div>
      {console.log('pokemon list', props.pokemonLists)}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <h1 >
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

      </main>
    </div>
  )
}

const mapStateToProps = (state:any)=>({
  user: state.user.user,
  pokemonLists: state.pokemon.pokemonLists
})

const mapDispatchToProps = (dispatch:any) =>({
  setUser: (user:any)=>dispatch(setUser(user)),
  retrievePokemonLists: (user:any)=>dispatch(retrievePokemonLists(user))
})

export default connect(mapStateToProps, mapDispatchToProps)(Home)
